# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: 'Close stale issues'

on:
  schedule:
  - cron: '43 0 * * *'

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue is being automatically closed due to lack of activity for 30 days. While the CARD team does it's best to keep up, sometimes we are unable to do so. Please re-open this issue if you still need assistance."
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-pr-labels: 'stale-exempt'
        remove-stale-when-updated: 'True'
        operations-per-run: 100
        days-before-stale: 30
        days-before-close: 7
